Revised docker from @iamamutt
tests/test_ingest.py::test_ingest_subjects PASSED
tests/test_ingest.py::test_ingest_sessions PASSED
tests/test_ingest.py::test_paramset_insert ERROR
tests/test_pipeline_generation.py::test_generate_pipeline PASSED
tests/test_populate.py::test_recording_info_populate PASSED
tests/test_populate.py::test_processing_populate ERROR

ERRORs because AttributeError: module 'collections' has no attribute 'Mapping'